/*
 * Light.c
 *
 *  Created on: May 10, 2024
 *      Author: Dell
 */
#include "Light.h"
void Red1Green2(){
	HAL_GPIO_WritePin(LED_RED1_GPIO_Port, LED_RED1_Pin, SET);
	HAL_GPIO_WritePin(LED_YELLOW1_GPIO_Port, LED_YELLOW1_Pin, RESET);
	HAL_GPIO_WritePin(LED_GREEN1_GPIO_Port, LED_GREEN1_Pin, RESET);
	HAL_GPIO_WritePin(LED_RED2_GPIO_Port, LED_RED2_Pin, RESET);
	HAL_GPIO_WritePin(LED_YELLOW2_GPIO_Port, LED_YELLOW2_Pin, RESET);
	HAL_GPIO_WritePin(LED_GREEN2_GPIO_Port, LED_GREEN2_Pin, SET);
}
void Red1Yellow2(){
	HAL_GPIO_WritePin(LED_RED1_GPIO_Port, LED_RED1_Pin, SET);
	HAL_GPIO_WritePin(LED_YELLOW1_GPIO_Port, LED_YELLOW1_Pin, RESET);
	HAL_GPIO_WritePin(LED_GREEN1_GPIO_Port, LED_GREEN1_Pin, RESET);
	HAL_GPIO_WritePin(LED_RED2_GPIO_Port, LED_RED2_Pin, RESET);
	HAL_GPIO_WritePin(LED_YELLOW2_GPIO_Port, LED_YELLOW2_Pin, SET);
	HAL_GPIO_WritePin(LED_GREEN2_GPIO_Port, LED_GREEN2_Pin, RESET);
}
void Green1Red2(){
	HAL_GPIO_WritePin(LED_RED1_GPIO_Port, LED_RED1_Pin, RESET);
	HAL_GPIO_WritePin(LED_YELLOW1_GPIO_Port, LED_YELLOW1_Pin, RESET);
	HAL_GPIO_WritePin(LED_GREEN1_GPIO_Port, LED_GREEN1_Pin, SET);
	HAL_GPIO_WritePin(LED_RED2_GPIO_Port, LED_RED2_Pin, SET);
	HAL_GPIO_WritePin(LED_YELLOW2_GPIO_Port, LED_YELLOW2_Pin, RESET);
	HAL_GPIO_WritePin(LED_GREEN2_GPIO_Port, LED_GREEN2_Pin, RESET);
}
void Yellow1Red2(){
	HAL_GPIO_WritePin(LED_RED1_GPIO_Port, LED_RED1_Pin, RESET);
	HAL_GPIO_WritePin(LED_YELLOW1_GPIO_Port, LED_YELLOW1_Pin, SET);
	HAL_GPIO_WritePin(LED_GREEN1_GPIO_Port, LED_GREEN1_Pin, RESET);
	HAL_GPIO_WritePin(LED_RED2_GPIO_Port, LED_RED2_Pin, SET);
	HAL_GPIO_WritePin(LED_YELLOW2_GPIO_Port, LED_YELLOW2_Pin, RESET);
	HAL_GPIO_WritePin(LED_GREEN2_GPIO_Port, LED_GREEN2_Pin, RESET);
}
void Green1Green2(){
	HAL_GPIO_TogglePin(LED_GREEN1_GPIO_Port, LED_GREEN1_Pin);
	HAL_GPIO_WritePin(LED_YELLOW1_GPIO_Port, LED_YELLOW1_Pin, RESET);
	HAL_GPIO_WritePin(LED_RED1_GPIO_Port, LED_RED1_Pin, RESET);
	HAL_GPIO_TogglePin(LED_GREEN2_GPIO_Port,LED_GREEN2_Pin );
	HAL_GPIO_WritePin(LED_YELLOW2_GPIO_Port, LED_YELLOW2_Pin, RESET);
	HAL_GPIO_WritePin(LED_RED2_GPIO_Port, LED_RED2_Pin, RESET);

}
void Red1Red2(){
	HAL_GPIO_TogglePin(LED_RED1_GPIO_Port, LED_RED1_Pin);
	HAL_GPIO_WritePin(LED_YELLOW1_GPIO_Port, LED_YELLOW1_Pin, RESET);
	HAL_GPIO_WritePin(LED_GREEN1_GPIO_Port, LED_GREEN1_Pin, RESET);
	HAL_GPIO_TogglePin(LED_RED2_GPIO_Port, LED_RED2_Pin);
	HAL_GPIO_WritePin(LED_YELLOW2_GPIO_Port, LED_YELLOW2_Pin, RESET);
	HAL_GPIO_WritePin(LED_GREEN2_GPIO_Port, LED_GREEN2_Pin, RESET);

}
void Yellow1Yellow2(){
	HAL_GPIO_TogglePin(LED_YELLOW1_GPIO_Port, LED_YELLOW1_Pin);
	HAL_GPIO_WritePin(LED_RED1_GPIO_Port, LED_RED1_Pin, RESET);
	HAL_GPIO_WritePin(LED_GREEN1_GPIO_Port, LED_GREEN1_Pin, RESET);
	HAL_GPIO_TogglePin(LED_YELLOW2_GPIO_Port,LED_YELLOW2_Pin );
	HAL_GPIO_WritePin(LED_RED2_GPIO_Port,LED_RED2_Pin , RESET);
	HAL_GPIO_WritePin(LED_GREEN2_GPIO_Port, LED_GREEN2_Pin, RESET);
}

void display7SEG(int num){
	switch (num){
	case 0:
			HAL_GPIO_WritePin(GPIOA, SEG0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG4_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG5_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG6_Pin, GPIO_PIN_SET);
			break;
		case 1:
			HAL_GPIO_WritePin(GPIOA, SEG0_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG3_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG4_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG5_Pin, GPIO_PIN_SET);
	    	HAL_GPIO_WritePin(GPIOA, SEG6_Pin, GPIO_PIN_SET);
			break;
		case 2:
			HAL_GPIO_WritePin(GPIOA, SEG0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG2_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG4_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG5_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG6_Pin, GPIO_PIN_RESET);
			break;
		case 3:
			HAL_GPIO_WritePin(GPIOA, SEG0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG4_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG5_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG6_Pin, GPIO_PIN_RESET);
			break;
		case 4:
			HAL_GPIO_WritePin(GPIOA, SEG0_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG3_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG4_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG5_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG6_Pin, GPIO_PIN_RESET);
			break;
		case 5:
			HAL_GPIO_WritePin(GPIOA, SEG0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG1_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG4_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG5_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG6_Pin, GPIO_PIN_RESET);
			break;
		case 6:
			HAL_GPIO_WritePin(GPIOA, SEG0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG1_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG4_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG5_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG6_Pin, GPIO_PIN_RESET);
			break;
		case 7:
			HAL_GPIO_WritePin(GPIOA, SEG0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG3_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG4_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG5_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG6_Pin, GPIO_PIN_SET);
			break;
		case 8:
			HAL_GPIO_WritePin(GPIOA, SEG0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG4_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG5_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG6_Pin, GPIO_PIN_RESET);
			break;
		case 9:
			HAL_GPIO_WritePin(GPIOA, SEG0_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG1_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG2_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG3_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG4_Pin, GPIO_PIN_SET);
			HAL_GPIO_WritePin(GPIOA, SEG5_Pin, GPIO_PIN_RESET);
			HAL_GPIO_WritePin(GPIOA, SEG6_Pin, GPIO_PIN_RESET);
			break;
		default:
			break;
	}
}
